### ISSUE TITLE
PF2E System Error Toast Warning

### ISSUE THREAD

**Issue by Armandeus66** [eXaminator/foundry-animation-preview#5]
When starting Foundry v 9 using Pathfinder 2E system version 3.12.2.10, this module causes a yellow toast warning which says the module does not indicate that it is compatible with this system. The warning states, "this module is unmaintained and may introduce stability issues into your game." Please update the manifest if the module is compatible. Thanks.

**Comment by eXaminator** [comment]
Thanks for your issue. This module should support every system. I don't plan to add all systems to the manifest. This I will add no system to the manifest. This seems a problem with the pf2e system if it expects every module to explicitly state system support. As far as I know this is nothing FVTT states as an expectation for modules.

I also don't know why it states the module is unmaintained, which is false.

**Comment by TMunsie** [comment]
PF2e system is not checking if you support PF2e. It is checking if you support Foundry V9. Your manifest indicates you are only compatible up to core 0.8.9

**Comment by Armandeus66** [comment]
I mistakenly wrote "compatible with this system" where I should have written "compatible with Foundry v. 9." My apologies.

**Comment by eXaminator** [comment]
Oh, im also sorry, because I was on the road and only now realised which module we're talking about (I thought this comment was on another one). So I guess we both made mistakes 😅

In this case, yes! I haven't updated this module in a while and I should release a v9 compatible version, and also check V10 compatibility. Thanks for the reminder.

**Comment by eXaminator** [comment]
I have finally(!) updated the module.json. It now supports v9 and also v10 (though I removed v8 Support, because I will no longer test that version).
